### ISSUE TITLE
Getting some weird permission issues when trying to install

### ISSUE THREAD

**Issue by matthewmueller** [yoshuawuyts/debug-to-json#1]
![img](https://cldup.com/U2cVuyZHQT.png)

Any ideas?

**Comment by yoshuawuyts** [comment]
Can recreate on `node@4`. Investigating.

**Comment by matthewmueller** [comment]
cool, fwiw it's been happening on node@0.12.7 as well

**Comment by yoshuawuyts** [comment]
fixed in `v1.0.5`. Not sure if this module is any good though, I'm happy to add you as a contributor if you are using this (':

**Comment by matthewmueller** [comment]
hahaha, I'm not sure either :-P. I have something in mind, but I'll let you know how it goes
